import {course1, course2, course3, course4, course5, course6, course7, course8, course9} from "../../assets/index.js";

export const coursesmenu = [

    {
        id: 1,
        category: "Photography",
        author: "Determined-Poitras",
        title: "Create An LMS Website With LearnPress",
        duration: "2 Weeks",
        students: 156,
        price: "Free",
        image: course1,
    },
    {
        id: 2,
        category: "Photography",
        author: "Determined-Poitras",
        title: "Design a website with ThimPress",
        duration: "2 Weeks",
        students: 156,
        price: "$49.0",
        image: course2,
    },
    {
        id: 3,
        category: "Photography",
        author: "Determined-Poitras",
        title: "Create an LMS Website with LearnPress",
        duration: "2 Weeks",
        students: 156,
        price: "Free",
        image: course3,
    },
    {
        id: 4,
        category: "Photography",
        author: "Determined-Poitras",
        title: "Create an LMS Website with LearnPress",
        duration: "2 Weeks",
        students: 156,
        price: "Free",
        image: course4,
    },
    {
        id: 5,
        category: "Photography",
        author: "Determined-Poitras",
        title: "Create An LMS Website With LearnPress",
        duration: "2 Weeks",
        students: 156,
        price: "Free",
        image: course5,
    },
    {
        id: 6,
        category: "Photography",
        author: "Determined-Poitras",
        title: "Create an LMS Website with LearnPress",
        duration: "2 Weeks",
        students: 156,
        price: "Free",
        image: course6,
    },
    {
        id: 7,
        author: "Looking for an amazing & well-functional LearnPress WordPress Theme?...",
        title: "Best LearnPress WordPress Theme Collection for 2023 ",
        data: "Jan 24, 2025",
        image: course7,
    },
    {
        id: 8,
        author: "Looking for an amazing & well-functional LearnPress WordPress Theme?...",
        title: "Best LearnPress WordPress Theme Collection for 2023",
        data: "Jan 24, 2025",
        image: course8,
    },
    {
        id: 9,
        author: "Looking for an amazing & well-functional LearnPress WordPress Theme?...",
        title: "Best LearnPress WordPress Theme Collection for 2023",
        data: "Jan 24, 2025",
        image: course9,
    },
];